version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dcf5636196aa409b75a0f7a73a314df4c8fc05d9b9fc0cad9b87ee64f2d6d2b1
    ports:
      - '127.0.0.1:5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
