#!/usr/bin/env python

import sys
from sampling import SampleOrgTest

def run():
    org_ids = [1, 2]
    test_ids = [52, 53]

    for org_id in org_ids:
        for test_id in test_ids:
            sot = SampleOrgTest(org_id, test_id)
            if not sot.qualifies():
                continue
            act_ids = sot.activity_ids()
            print len(act_ids)
            sample_ids = sot.sample_activity_ids(10)
            print org_id, test_id, sample_ids

            for act_id in sample_ids:
                print act_id
                act = sot.xml_of_activity(act_id)
                print act
                # lxml.etree.tostring(act)



if __name__ == '__main__':
    run()    
