"""Create component and indicator tables.

Revision ID: 17b8f45cc23d
Revises: 307e909bbc0d
Create Date: 2019-04-23 10:26:12.570556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b8f45cc23d'
down_revision = '307e909bbc0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicator',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('indicator_type', sa.String(length=255), nullable=False),
    sa.Column('component_id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.String(length=255), nullable=False),
    sa.Column('has_format', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator')
    op.drop_table('component')
    # ### end Alembic commands ###
