"""Rename organisation column, for consistency

Revision ID: 307e909bbc0d
Revises: 996d08b98210
Create Date: 2019-04-21 16:33:02.458423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307e909bbc0d'
down_revision = '996d08b98210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('organisation_id', sa.String(length=255), nullable=True))
    op.drop_constraint('role_organisation_fkey', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'organisation', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('role', 'organisation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('organisation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key('role_organisation_fkey', 'role', 'organisation', ['organisation'], ['id'], ondelete='CASCADE')
    op.drop_column('role', 'organisation_id')
    # ### end Alembic commands ###
