"""Add (unique) username to user; make email non-unique.

Revision ID: 873290f6bdb9
Revises: d406c28e9227
Create Date: 2019-04-20 00:05:50.454975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873290f6bdb9'
down_revision = 'd406c28e9227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_user', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tracker_user_username'), 'tracker_user', ['username'], unique=True)
    op.drop_constraint('tracker_user_email_key', 'tracker_user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tracker_user_email_key', 'tracker_user', ['email'])
    op.drop_index(op.f('ix_tracker_user_username'), table_name='tracker_user')
    op.drop_column('tracker_user', 'username')
    # ### end Alembic commands ###
