"""empty message

Revision ID: 93abde4212f8
Revises: 97b16ecf9e0e
Create Date: 2019-04-19 15:38:17.320085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93abde4212f8'
down_revision = '97b16ecf9e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('organisation', 'test_condition',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', 'test_condition',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('organisation', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
