"""empty message

Revision ID: 97b16ecf9e0e
Revises: f1054dfbf69d
Create Date: 2019-04-19 14:20:36.193414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b16ecf9e0e'
down_revision = 'f1054dfbf69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('registry_slug', sa.String(length=255), nullable=True))
    op.add_column('organisation', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('organisation', sa.Column('test_condition', sa.String(length=255), nullable=False))
    op.drop_constraint('organisation_org_id_key', 'organisation', type_='unique')
    op.create_unique_constraint(None, 'organisation', ['slug'])
    op.drop_column('organisation', 'org_id')
    op.drop_column('organisation', 'registry_handle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('registry_handle', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organisation', sa.Column('org_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organisation', type_='unique')
    op.create_unique_constraint('organisation_org_id_key', 'organisation', ['org_id'])
    op.drop_column('organisation', 'test_condition')
    op.drop_column('organisation', 'slug')
    op.drop_column('organisation', 'registry_slug')
    # ### end Alembic commands ###
