"""empty message

Revision ID: ef541e907756
Revises: 901b6a3b86de
Create Date: 2019-04-21 15:35:51.718486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef541e907756'
down_revision = '901b6a3b86de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organisation_slug_key', 'organisation', type_='unique')
    op.drop_column('organisation', 'slug')
    op.drop_constraint('role_organisation_fkey', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'organisation', ['organisation'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key('role_organisation_fkey', 'role', 'organisation', ['organisation'], ['slug'], ondelete='CASCADE')
    op.add_column('organisation', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('organisation_slug_key', 'organisation', ['slug'])
    # ### end Alembic commands ###
